// src/components/Faculty/CoursesPage.jsx
import React, { useState, useEffect } from 'react';
import { useAuthStore } from '../../store/AuthStore';
import { toast } from 'react-toastify';
import FaceRecognitionModal from '../Shared/FaceRecognitionModal';
import { Book, Users, Clock } from 'lucide-react';

const CoursesPage = () => {
    const [courses, setCourses] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [selectedCourse, setSelectedCourse] = useState(null);
    const [isModalOpen, setIsModalOpen] = useState(false);

    const token = useAuthStore((state) => state.session.access_token);

    useEffect(() => {
        const fetchLectures = async () => {
            try {
                // Fetch today's lectures generated by the timetable engine
                const response = await fetch(`${import.meta.env.VITE_API_HOST}/api/faculty/lectures/today`, {
                    headers: { 'Authorization': `Bearer ${token}` }
                });
                const { data } = await response.json();
                setCourses(data || []);
            } catch (error) {
                console.error("Failed to fetch lectures:", error);
                toast.error("Could not fetch today's lectures.");
            } finally {
                setIsLoading(false);
            }
        };
        fetchLectures();
    }, [token]);

    const handleStartSessionClick = (course) => {
        setSelectedCourse(course);
        setIsModalOpen(true);
    };

    const handleRecognitionSuccess = async () => {
        if (!selectedCourse) return;

        try {
            // Endpoints use the CourseSession (Lecture) ID now
            const response = await fetch(`${import.meta.env.VITE_API_HOST}/api/faculty/lectures/${selectedCourse._id}/start`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}` }
            });

            if (response.ok) {
                toast.success(`Lecture for ${selectedCourse.course.name} is now LIVE!`);
                // Update local state to show it's live
                setCourses(courses.map(c => 
                    c._id === selectedCourse._id ? { ...c, status: 'live' } : c
                ));
            } else {
                toast.error("Failed to start the lecture.");
            }
        } catch (error) {
            console.error("Error starting session:", error);
            toast.error("An error occurred while starting the lecture.");
        }
    };


    const handleEndSessionClick = async (lecture) => {
        try {
            const response = await fetch(`${import.meta.env.VITE_API_HOST}/api/faculty/lectures/${lecture._id}/end`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}` }
            });

            if (response.ok) {
                toast.success(`Lecture for ${lecture.course.name} ended.`);
                setCourses(courses.map(c => 
                    c._id === lecture._id ? { ...c, status: 'completed' } : c
                ));
            } else {
                toast.error("Failed to end the lecture.");
            }
        } catch (error) {
            console.error("Error ending session:", error);
            toast.error("An error occurred while ending the lecture.");
        }
    };

    if (isLoading) {
        return <div>Loading courses...</div>;
    }

    return (
        <div className="container mx-auto p-4">
            <h1 className="text-3xl font-bold mb-6 dark:text-white">Today's Lectures</h1>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {courses.length === 0 && (
                    <p className="text-gray-500">You have no assigned lectures for today.</p>
                )}
                {courses.map((lecture) => (
                    <div key={lecture._id} className="glass-card p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow border-t-4 border-purple-500">
                        <div className="flex items-center mb-4">
                            <Book className="text-purple-500 mr-3" />
                            <h2 className="text-xl font-semibold dark:text-white">{lecture.course?.name || 'Unknown Course'}</h2>
                        </div>
                        <p className="text-gray-600 dark:text-slate-400 mb-2">Code: {lecture.course?.code}</p>
                        <p className="text-gray-600 dark:text-slate-400 mb-4">Time: {lecture.scheduledStartTime} - {lecture.scheduledEndTime}</p>
                        <div className="flex items-center text-gray-600 dark:text-slate-400 mb-6">
                            <Clock className="mr-2" />
                            <span className="font-bold uppercase text-xs tracking-wider" style={{ color: lecture.status === 'live' ? '#22c55e' : '#f59e0b' }}>
                                Status: {lecture.status}
                            </span>
                        </div>
                        {lecture.status === 'scheduled' ? (
                            <button
                                onClick={() => handleStartSessionClick(lecture)}
                                className="w-full flex items-center justify-center px-4 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 transition-colors"
                            >
                                <Clock className="mr-2 w-4 h-4" />
                                Start Lecture
                            </button>
                        ) : lecture.status === 'live' ? (
                            <button
                                onClick={() => handleEndSessionClick(lecture)}
                                className="w-full flex items-center justify-center px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 transition-colors"
                            >
                                End Lecture
                            </button>
                        ) : (
                            <button disabled className="w-full flex items-center justify-center px-4 py-2 bg-gray-400 text-white rounded-md cursor-not-allowed">
                                Completed
                            </button>
                        )}
                    </div>
                ))}
            </div>
             <FaceRecognitionModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                onSuccess={handleRecognitionSuccess}
                title="Faculty Verification"
            />
        </div>
    );
};

export default CoursesPage;